# Generated by Django 5.1.4 on 2024-12-30 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_course_instructor_remove_course_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
