# Generated by Django 5.1.4 on 2024-12-30 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_lesson_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='is_complete',
            new_name='completed',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='complete',
            new_name='completed',
        ),
    ]
